server:
  port: 8082


eureka:
  client: # 客户端进行Eureka注册的配置
    service-url:
      defaultZone: http://eureka:eureka@eureka1:7001/eureka,http://eureka:eureka@eureka2:7002/eureka,http://eureka:eureka@eureka3:7003/eureka
  instance:
    instance-id: provider2
    hostname: provider2
    prefer-ip-address: true


spring:
  application:
    name: provider


logging:
  level:
    com.zy.study.mapper: debug

info:
  app.name: provider2
  company.name: study
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$
